// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPtBQdDgs84ZM7DuhjxecTmIrWPiVynw',
    appId: '1:121444943855:web:c67d4300c2825136e3581a',
    messagingSenderId: '121444943855',
    projectId: 'family-economy-d1b4d',
    authDomain: 'family-economy-d1b4d.firebaseapp.com',
    storageBucket: 'family-economy-d1b4d.firebasestorage.app',
    measurementId: 'G-G0C3TVQRNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69a9OvQtObOfq5XDwhrZRuZbf6bMCXcg',
    appId: '1:121444943855:android:e586a3a9ed09874be3581a',
    messagingSenderId: '121444943855',
    projectId: 'family-economy-d1b4d',
    storageBucket: 'family-economy-d1b4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjHOXJqUNhYZKA53NhEM7Vf2Mxw7RhsEY',
    appId: '1:121444943855:ios:32481f9213ac99fae3581a',
    messagingSenderId: '121444943855',
    projectId: 'family-economy-d1b4d',
    storageBucket: 'family-economy-d1b4d.firebasestorage.app',
    iosBundleId: 'com.example.familyEconomy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjHOXJqUNhYZKA53NhEM7Vf2Mxw7RhsEY',
    appId: '1:121444943855:ios:32481f9213ac99fae3581a',
    messagingSenderId: '121444943855',
    projectId: 'family-economy-d1b4d',
    storageBucket: 'family-economy-d1b4d.firebasestorage.app',
    iosBundleId: 'com.example.familyEconomy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPtBQdDgs84ZM7DuhjxecTmIrWPiVynw',
    appId: '1:121444943855:web:8b58acc255cb188ce3581a',
    messagingSenderId: '121444943855',
    projectId: 'family-economy-d1b4d',
    authDomain: 'family-economy-d1b4d.firebaseapp.com',
    storageBucket: 'family-economy-d1b4d.firebasestorage.app',
    measurementId: 'G-S3CWZ8K6HH',
  );

}